/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (push,OBJECT_ALIGNMENT)
#endif

#ifndef CORE_API
#define CORE_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern CORE_API FName CORE_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class CORE_API URegistry : public UObject
{
public:
    DECLARE_FUNCTION(execLoadRegistryProperty);
    DECLARE_FUNCTION(execGetRegistryProperties);
    DECLARE_FUNCTION(execGetPreferences);
    DECLARE_FUNCTION(execGetRegistryObjects);
    DECLARE_CLASS(URegistry,UObject,0,Core)
    NO_DEFAULT_CONSTRUCTOR(URegistry)
};

#endif

AUTOGENERATE_FUNCTION(URegistry,-1,execLoadRegistryProperty);
AUTOGENERATE_FUNCTION(URegistry,-1,execGetRegistryProperties);
AUTOGENERATE_FUNCTION(URegistry,-1,execGetPreferences);
AUTOGENERATE_FUNCTION(URegistry,-1,execGetRegistryObjects);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(URegistry)
#endif // VERIFY_CLASS_SIZES
