/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack(push,OBJECT_ALIGNMENT)
#endif

#ifndef ALAUDIO_API
#define ALAUDIO_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern ALAUDIO_API FName ALAUDIO_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

class ALAUDIO_API AEFXZone : public AZoneInfo
{
public:
	BYTE Ambients GCC_ALIGN(4);
	BITFIELD bUserDefined:1 GCC_ALIGN(4);
	FLOAT EFXflAirAbsorptionGainHF GCC_ALIGN(4);
	FLOAT EFXflDecayHFRatio;
	FLOAT EFXflDecayLFRatio;
	FLOAT EFXflDecayTime;
	FLOAT EFXflDensity;
	FLOAT EFXflDiffusion;
	FLOAT EFXflEchoDepth;
	FLOAT EFXflEchoTime;
	FLOAT EFXflGain;
	FLOAT EFXflGainHF;
	FLOAT EFXflGainLF;
	FLOAT EFXflHFReference;
	FLOAT EFXflLFReference;
	FLOAT EFXflLateReverbDelay;
	FLOAT EFXflLateReverbGain;
	FLOAT EFXflRoomRolloffFactor;
	BITFIELD EFXiDecayHFLimit:1 GCC_ALIGN(4);
	DECLARE_CLASS(AEFXZone,AZoneInfo,0,ALAudio)
	NO_DEFAULT_CONSTRUCTOR(AEFXZone)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (pop)
#endif

#ifdef VERIFY_CLASS_SIZES
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,Ambients)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflAirAbsorptionGainHF)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflDecayHFRatio)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflDecayLFRatio)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflDecayTime)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflDensity)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflDiffusion)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflEchoDepth)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflEchoTime)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflGain)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflGainHF)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflGainLF)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflHFReference)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflLFReference)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflLateReverbDelay)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflLateReverbGain)
//VERIFY_CLASS_OFFSET_NODIE(A,EFXZone,EFXflRoomRolloffFactor)
VERIFY_CLASS_SIZE_NODIE(AEFXZone)
#endif // VERIFY_CLASS_SIZES
