/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (push,OBJECT_ALIGNMENT)
#endif

#ifndef SCRIPTEDAIED_API
#define SCRIPTEDAIED_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern SCRIPTEDAIED_API FName SCRIPTEDAIED_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

class SCRIPTEDAIED_API UNativeHook : public UObject
{
public:
	class UFont* MainFont GCC_PACK(INT_ALIGNMENT);
	class UTexture* BgTexture;
	class UTexture* ArrowTexture;
	class UTexture* SphereTexture;
	class UTexture* GroupBGTexture;
	class UTexture* HaloTexture;
	FPlane BGColor;
	DECLARE_FUNCTION(execShowEdWindow);
	DECLARE_CLASS(UNativeHook,UObject,0,ScriptedAIEd)
	NO_DEFAULT_CONSTRUCTOR(UNativeHook)
};

#endif

AUTOGENERATE_FUNCTION(UNativeHook,-1,execShowEdWindow);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE_SLOW(U,NativeHook,MainFont)
VERIFY_CLASS_OFFSET_NODIE_SLOW(U,NativeHook,BgTexture)
VERIFY_CLASS_OFFSET_NODIE_SLOW(U,NativeHook,ArrowTexture)
VERIFY_CLASS_OFFSET_NODIE_SLOW(U,NativeHook,SphereTexture)
VERIFY_CLASS_OFFSET_NODIE_SLOW(U,NativeHook,GroupBGTexture)
VERIFY_CLASS_OFFSET_NODIE_SLOW(U,NativeHook,HaloTexture)
VERIFY_CLASS_OFFSET_NODIE_SLOW(U,NativeHook,BGColor)
VERIFY_CLASS_SIZE_NODIE(UNativeHook)
#endif // VERIFY_CLASS_SIZES
