/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef UPAK_API
#define UPAK_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern UPAK_API FName UPAK_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class UPAK_API APathNodeIterator : public AActor
{
public:
    class ANavigationPoint* NodePath[64];
    INT NodeCount;
    INT NodeIndex;
    INT NodeCost;
    FVector NodeStart;
    DECLARE_FUNCTION(execGetLastVisible);
    DECLARE_FUNCTION(execGetLast);
    DECLARE_FUNCTION(execGetNext);
    DECLARE_FUNCTION(execGetCurrent);
    DECLARE_FUNCTION(execGetPrevious);
    DECLARE_FUNCTION(execGetFirst);
    DECLARE_FUNCTION(execBuildPath);
    DECLARE_CLASS(APathNodeIterator,AActor,0|CLASS_Transient)
    #include "APathNodeIterator.h"
};


class UPAK_API APawnPathNodeIterator : public APathNodeIterator
{
public:
    class APawn* Pawn;
    DECLARE_FUNCTION(execSetPawn);
    DECLARE_CLASS(APawnPathNodeIterator,APathNodeIterator,0|CLASS_Transient)
    #include "APawnPathNodeIterator.h"
};

#endif

AUTOGENERATE_FUNCTION(APawnPathNodeIterator,-1,execSetPawn);
AUTOGENERATE_FUNCTION(APathNodeIterator,-1,execGetLastVisible);
AUTOGENERATE_FUNCTION(APathNodeIterator,-1,execGetLast);
AUTOGENERATE_FUNCTION(APathNodeIterator,-1,execGetNext);
AUTOGENERATE_FUNCTION(APathNodeIterator,-1,execGetCurrent);
AUTOGENERATE_FUNCTION(APathNodeIterator,-1,execGetPrevious);
AUTOGENERATE_FUNCTION(APathNodeIterator,-1,execGetFirst);
AUTOGENERATE_FUNCTION(APathNodeIterator,-1,execBuildPath);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
