/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (push,OBJECT_ALIGNMENT)
#endif

#ifndef EDITOR_API
#define EDITOR_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern EDITOR_API FName EDITOR_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(Build)

#ifndef NAMES_ONLY


struct UBrushBuilder_eventBuild_Parms
{
    BITFIELD ReturnValue;
};
class EDITOR_API UBrushBuilder : public UObject
{
public:
    FStringNoInit BitmapFilename;
    FStringNoInit ToolTip;
    TArrayNoInit<FVector> Vertices;
    TArrayNoInit<FBuilderPoly> Polys;
    FName Group;
    BITFIELD MergeCoplanars:1;
    DECLARE_FUNCTION(execPolyEnd);
    DECLARE_FUNCTION(execPolyi);
    DECLARE_FUNCTION(execPolyBegin);
    DECLARE_FUNCTION(execPoly4i);
    DECLARE_FUNCTION(execPoly3i);
    DECLARE_FUNCTION(execVertex3f);
    DECLARE_FUNCTION(execVertexv);
    DECLARE_FUNCTION(execBadParameters);
    DECLARE_FUNCTION(execGetPolyCount);
    DECLARE_FUNCTION(execGetVertex);
    DECLARE_FUNCTION(execGetVertexCount);
    DECLARE_FUNCTION(execEndBrush);
    DECLARE_FUNCTION(execBeginBrush);
    BITFIELD eventBuild()
    {
        UBrushBuilder_eventBuild_Parms Parms;
        Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(EDITOR_Build),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(UBrushBuilder,UObject,0,Editor)
    #include "UBrushBuilder.h"
};

#endif

AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyEnd);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyi);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyBegin);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly4i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly3i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertex3f);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertexv);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBadParameters);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetPolyCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertex);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertexCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execEndBrush);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBeginBrush);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(U,BrushBuilder,BitmapFilename)
VERIFY_CLASS_OFFSET_NODIE(U,BrushBuilder,ToolTip)
VERIFY_CLASS_OFFSET_NODIE(U,BrushBuilder,Vertices)
VERIFY_CLASS_OFFSET_NODIE(U,BrushBuilder,Polys)
VERIFY_CLASS_OFFSET_NODIE(U,BrushBuilder,Group)
VERIFY_CLASS_SIZE_NODIE(UBrushBuilder)
#endif // VERIFY_CLASS_SIZES
