/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (push,OBJECT_ALIGNMENT)
#endif

#ifndef USQLITE_API
#define USQLITE_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern USQLITE_API FName USQLITE_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

class USQLITE_API ASQLite : public AInfo
{
public:
	sqlite3* database GCC_PACK(INT_ALIGNMENT);
	DECLARE_FUNCTION(execGetQueries);
	DECLARE_FUNCTION(execQuery);
	DECLARE_FUNCTION(execCloseDatabase);
	DECLARE_FUNCTION(execInitDatabase);
	DECLARE_CLASS(ASQLite,AInfo,0,USQLite)

	ASQLite();
	void Destroy();
	UBOOL sqlite_err(int InErr);
};

#endif

AUTOGENERATE_FUNCTION(ASQLite,-1,execGetQueries);
AUTOGENERATE_FUNCTION(ASQLite,-1,execQuery);
AUTOGENERATE_FUNCTION(ASQLite,-1,execCloseDatabase);
AUTOGENERATE_FUNCTION(ASQLite,-1,execInitDatabase);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE_SLOW(A,SQLite,database)
VERIFY_CLASS_SIZE_NODIE(ASQLite)
#endif // VERIFY_CLASS_SIZES
